apiVersion: v1
entries:
  one-container-app:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2023-03-23T12:49:19.510062+01:00"
    description: A Helm chart for Kubernetes
    digest: bca6a4384b51bbfb154eaa3cee275614014897b52a8bbdaea7ae08746a50168b
    name: one-container-app
    type: application
    urls:
    - one-container-app-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-23T12:49:19.506618+01:00"
