apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    {{- toYaml .Values.service.ports | nindent 4}}
 